name: health_bot
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.1
  get: ^4.6.6
  url_launcher: ^6.2.6
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.15.8
  lottie: ^3.1.2
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  responsive_builder: ^0.7.0
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  google_sign_in: ^6.2.1
  shimmer_pro: ^0.0.6
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  speech_to_text: ^6.6.0
  shared_preferences: ^2.2.3
  percent_indicator: ^4.2.3
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #-------------- LOCAL ASSETS --------------#
  assets:
    - assets/images/
    - assets/lottie/
    - assets/logo/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/welcome/
    - assets/images/memoji/
    - assets/images/house/

  #-------------- LOCAL FONTS --------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/coolvetica_regular_italic.otf
        - asset: assets/fonts/coolvetica_regular.otf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
 



        
