// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbcslRePnopE0giI1utyDs_cS7e-5dG0',
    appId: '1:977325198232:web:a81fa2aeadc6549319b9ed',
    messagingSenderId: '977325198232',
    projectId: 'healthbot-14d3b',
    authDomain: 'healthbot-14d3b.firebaseapp.com',
    storageBucket: 'healthbot-14d3b.appspot.com',
    measurementId: 'G-0T0CEJHNBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQILKk7OYC56Kn666Ls_QcYMhGsXou7-g',
    appId: '1:977325198232:android:18864055f5bd4d9919b9ed',
    messagingSenderId: '977325198232',
    projectId: 'healthbot-14d3b',
    storageBucket: 'healthbot-14d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjXNwDkOO3sch4_yU5UxllRAHuLKv-kns',
    appId: '1:977325198232:ios:b72238c72dc105ab19b9ed',
    messagingSenderId: '977325198232',
    projectId: 'healthbot-14d3b',
    storageBucket: 'healthbot-14d3b.appspot.com',
    iosBundleId: 'com.example.healthBot',
  );
}
